[mypy]
python_version = 3.8
exclude = setup.py
show_error_codes = True
warn_unused_ignores = False
check_untyped_defs = True

[mypy-gdown]
ignore_missing_imports = True
[mypy-skrobot.*]
ignore_missing_imports = True
[mypy-pynput.*]
ignore_missing_imports = True
[mypy-pybullet]
ignore_missing_imports = True
[mypy-pybullet_data]
ignore_missing_imports = True
[mypy-pygame]
ignore_missing_imports = True
